module4-task1
htmlacademy-javascript/1591651-kekstagram-22 pull request #4
Opened 2021-02-16 16:51 UTC by Antony703

2021-02-17 05:56 UTC, craz3r requested changes

2021-02-17 05:56 UTC, craz3r commented on js/util.js
> +const COMMENT_MESSAGES = [
Константы можно вынести в отдельный модуль

2021-02-17 05:56 UTC, craz3r commented on js/util.js
> +const createComments = (number_of_comments) => {
Функции для создания фейковых данных лучше вынести в отдельный модуль (mock.js например), так как они не совсем подходят под определение утилитарных функций

2021-02-17 15:08 UTC, Antony703 commented on js/util.js
> +const COMMENT_MESSAGES = [
Никита я вынес константы в отдельный модуль, но вызов их в другом модуле. Линтер пишет мне ошибку, что они описаны, но не используются. Мне нужно их импортировать, верно?

2021-02-18 08:37 UTC, craz3r commented on js/util.js
> +const COMMENT_MESSAGES = [
Совершенно верно

2021-02-18 08:39 UTC, craz3r commented on js/util.js
> +const createComments = (number_of_comments) => {
Сейчас в модуле mock.js находятся как функции по генерации моков, так и утилитарные функции, (getRandomNatural , isStringLengthCorrect), в предыдущем комментарии я писал как раз о том что у них разные назначения, соответственно они должны находиться в разных модулях

2021-02-28 16:20 UTC, merged